/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AudioTrack } from "./AudioTrack";
import { AudioTrackCountArgs } from "./AudioTrackCountArgs";
import { AudioTrackFindManyArgs } from "./AudioTrackFindManyArgs";
import { AudioTrackFindUniqueArgs } from "./AudioTrackFindUniqueArgs";
import { CreateAudioTrackArgs } from "./CreateAudioTrackArgs";
import { UpdateAudioTrackArgs } from "./UpdateAudioTrackArgs";
import { DeleteAudioTrackArgs } from "./DeleteAudioTrackArgs";
import { AudioTrackService } from "../audioTrack.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => AudioTrack)
export class AudioTrackResolverBase {
  constructor(
    protected readonly service: AudioTrackService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "AudioTrack",
    action: "read",
    possession: "any",
  })
  async _audioTracksMeta(
    @graphql.Args() args: AudioTrackCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [AudioTrack])
  @nestAccessControl.UseRoles({
    resource: "AudioTrack",
    action: "read",
    possession: "any",
  })
  async audioTracks(
    @graphql.Args() args: AudioTrackFindManyArgs
  ): Promise<AudioTrack[]> {
    return this.service.audioTracks(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => AudioTrack, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "AudioTrack",
    action: "read",
    possession: "own",
  })
  async audioTrack(
    @graphql.Args() args: AudioTrackFindUniqueArgs
  ): Promise<AudioTrack | null> {
    const result = await this.service.audioTrack(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => AudioTrack)
  @nestAccessControl.UseRoles({
    resource: "AudioTrack",
    action: "create",
    possession: "any",
  })
  async createAudioTrack(
    @graphql.Args() args: CreateAudioTrackArgs
  ): Promise<AudioTrack> {
    return await this.service.createAudioTrack({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => AudioTrack)
  @nestAccessControl.UseRoles({
    resource: "AudioTrack",
    action: "update",
    possession: "any",
  })
  async updateAudioTrack(
    @graphql.Args() args: UpdateAudioTrackArgs
  ): Promise<AudioTrack | null> {
    try {
      return await this.service.updateAudioTrack({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => AudioTrack)
  @nestAccessControl.UseRoles({
    resource: "AudioTrack",
    action: "delete",
    possession: "any",
  })
  async deleteAudioTrack(
    @graphql.Args() args: DeleteAudioTrackArgs
  ): Promise<AudioTrack | null> {
    try {
      return await this.service.deleteAudioTrack(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
