/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ModelTrainingSessionService } from "../modelTrainingSession.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ModelTrainingSessionCreateInput } from "./ModelTrainingSessionCreateInput";
import { ModelTrainingSession } from "./ModelTrainingSession";
import { ModelTrainingSessionFindManyArgs } from "./ModelTrainingSessionFindManyArgs";
import { ModelTrainingSessionWhereUniqueInput } from "./ModelTrainingSessionWhereUniqueInput";
import { ModelTrainingSessionUpdateInput } from "./ModelTrainingSessionUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ModelTrainingSessionControllerBase {
  constructor(
    protected readonly service: ModelTrainingSessionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ModelTrainingSession })
  @nestAccessControl.UseRoles({
    resource: "ModelTrainingSession",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createModelTrainingSession(
    @common.Body() data: ModelTrainingSessionCreateInput
  ): Promise<ModelTrainingSession> {
    return await this.service.createModelTrainingSession({
      data: data,
      select: {
        createdAt: true,
        datasetName: true,
        id: true,
        progress: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ModelTrainingSession] })
  @ApiNestedQuery(ModelTrainingSessionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ModelTrainingSession",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async modelTrainingSessions(
    @common.Req() request: Request
  ): Promise<ModelTrainingSession[]> {
    const args = plainToClass(ModelTrainingSessionFindManyArgs, request.query);
    return this.service.modelTrainingSessions({
      ...args,
      select: {
        createdAt: true,
        datasetName: true,
        id: true,
        progress: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ModelTrainingSession })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ModelTrainingSession",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async modelTrainingSession(
    @common.Param() params: ModelTrainingSessionWhereUniqueInput
  ): Promise<ModelTrainingSession | null> {
    const result = await this.service.modelTrainingSession({
      where: params,
      select: {
        createdAt: true,
        datasetName: true,
        id: true,
        progress: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ModelTrainingSession })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ModelTrainingSession",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateModelTrainingSession(
    @common.Param() params: ModelTrainingSessionWhereUniqueInput,
    @common.Body() data: ModelTrainingSessionUpdateInput
  ): Promise<ModelTrainingSession | null> {
    try {
      return await this.service.updateModelTrainingSession({
        where: params,
        data: data,
        select: {
          createdAt: true,
          datasetName: true,
          id: true,
          progress: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ModelTrainingSession })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ModelTrainingSession",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteModelTrainingSession(
    @common.Param() params: ModelTrainingSessionWhereUniqueInput
  ): Promise<ModelTrainingSession | null> {
    try {
      return await this.service.deleteModelTrainingSession({
        where: params,
        select: {
          createdAt: true,
          datasetName: true,
          id: true,
          progress: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
